:Title: OGC GeoHEIF SWG charter
:titletext: {Title}
:doctype: book
:encoding: utf-8
:lang: en
:toc:
:toc-placement!:
:toclevels: 4
:numbered:
:sectanchors:
:source-highlighter: pygments

<<<
[cols = ">",frame = "none",grid = "none"]
|===
|{set:cellbgcolor:#FFFFFF}
|[big]*Open Geospatial Consortium*
|Submission Date: <yyyy-mm-dd>
|Approval Date:   <yyyy-mm-dd>
|Internal reference number of this OGC(R) document:    25-039
|Category: OGC(R) Standards Working Group Charter
|Authors:   Joan Maso and Nuria Julia
|===

[cols = "^", frame = "none"]
|===
|[big]*{titletext}*
|===

[cols = "^", frame = "none", grid = "none"]
|===
|*Copyright notice*
|Copyright (C) 2025 Open Geospatial Consortium
|To obtain additional rights of use, visit http://www.opengeospatial.org/legal/
|===

<<<

////
Version of 2018-12-12
Some Instructions
This document is the template to be used for proposing the formation of a new Standards Working Group (SWG).

The first step is to complete the SWG Charter for the proposed new SWG.

The next step is to email the draft SWG charter to the Technical Committee Chair (TCC).  The TCC will review the draft charter and make any necessary comments and provide guidance.

Finally, once the Charter is ready, the SWG charter will be posted to the OGC Pending Documents and the vote process in the Technical Committee Policies and Procedures will start.

Any questions, please contact OGC staff.
////

To: OGC members & interested parties

A new OGC Standards Working Group is being formed. The OGC members listed below have proposed the OGC GeoHEIF SWG.  The SWG proposal provided in this document meets the requirements of the OGC Technical Committee (TC) Policies and Procedures.

The SWG name, statement of purpose, scope, list of deliverables, audience, and language specified in the proposal will constitute the SWG's official charter. Technical discussions may occur no sooner than the SWG's first meeting.

This SWG will operate under the OGC IPR Policy. The eligibility requirements for becoming a participant in the SWG at the first meeting (see details below) are that:

* You must be an employee of an OGC member organization or an individual
member of OGC;

* The OGC member must have signed the OGC Membership agreement;

* You must notify the SWG chair of your intent to participate to the first meeting. Members may do so by logging onto the OGC Portal and navigating to the Observer page and clicking on the link for the SWG they wish to join and;

* You must attend meetings of the SWG. The first meeting of this SWG is at the time and date fixed below. Attendance may be by teleconference.

Of course, participants also may join the SWG at any time. The OGC and the SWG welcomes all interested parties.

Non-OGC members who wish to participate may contact us about joining the OGC. In addition, the public may access some of the resources maintained for each SWG: the SWG public description, the SWG Charter, Change Requests, and public comments, which will be linked from the SWG’s page.

Please feel free to forward this announcement to any other appropriate lists. The OGC is an open standards organization; we encourage your feedback.

== Purpose of the Standards Working Group

////
Proposers will describe the purpose of the Standards Working Group and its overall mission in relation to OGC processes, the OGC Standards baseline, and OGC’s business plan.
////
The HEIF format is a multipart format that is defined by Moving Picture Experts Group (MPEG). In addition to camera footage,  adding the georeference information, HEIF can be used to store geospatial imagery. To do that, adding the georeference information is necessary like other formats has done in the past (e.g. GeoTIFF, JPEG2000, etc). Extending this to other metadata should be possible.

A future GeoHEIF (Geographic High Efficiency Image Format) specification aims to define HEIF properties to include the georeference information in one or more image items. In addition, other HEIF properties can be added to define the semantics of dimensions and cell properties that together enable converting HEIF into a datacube container. The GeoHEIF approach was demonstrated and tested in Testbed 20.

The initial purpose of this SWG will be to review the work done in the Testbed 20, in particular the OGC 24-038 OGC Testbed 20 GEOINT Imagery Media for ISR (GIMI) Specification Report, as well as the work that will be done in Testbed 21 on the GIMI extensions for HEIF, bring them to the attention to the OGC Technical Committee at large and create drafts of a OGC standards that can be incorporated as part of the OGC practices.

The work should work with other SWG groups (such GeoTIFF and GMLJP2) to find an approach that can be adopted by as many formats as possible  multipart. So, the work to be done is similar to the one previously done by the GeoTIFF SWG but taking into account a more open approach based on a mixture of binary sections with text sections (e.g. fragment based on JSON, turtle or XML encodings), something that was not considered at the beginning of the GeoTIFF work and was accepted by the GMLJP2 SWG.

== Business value proposition

////
This section provides a statement describing the value of this standards activity in relation to the OGC Membership, the geospatial community, and the wider IT community. This statement can be in terms of the interoperability problem being solved, processing Change requests to meet market (and Member requirements), a policy requirement and/or some other business value proposition. The proposition described in this section does not have to be in economic terms.
////


The HEIF format is becoming important as it has been designed to support big imagery as well as high resolution video. It is expected that in a few years its adoption will increase by the community. 
With the standards proposed by this group, we will ensure that georeference of imagery will not be ignored by the community and that image approaches, such as the datacubes, will be supported by the HEIF format without losing metadata. At this moment there is no format with the capabilities to export and exchange big datacubes in a single file and the HEIF is designed with capacities that can be optimal for such a purpose. This way, the format will form the basis for sharing a large existing collection of geospatial images, coverage data, animations and video, what clearly benefits some OGC members.

An approach that can be shared by some formats beyond HEIF will favour the community as no metadata lost will happen in a format transformation, reducing cost of data exchange among actors.

== Scope of work


////
This section describes the scope of work (SOW) for the work of the SWG. There are typically at least three (3) cases that justify the formation of a SWG: A group of members decide to develop a new OGC candidate Standard from scratch, there is a draft submission being discussed by OGC members, or there are outstanding Change Requests for an existing OGC Standard and a revision is required.

The following describes the characteristics of a SOW for each of these cases.

For a SWG focused on defining and documenting a new OGC candidate Standard from “scratch,” the SOW SHALL include a statement of the requirements and use cases for the candidate Standard being developed. The SOW SHALL also include a justification statement for developing a new candidate OGC Standard. The SOW SHALL also describe how the new candidate Standard is related to the existing OGC Standards baseline and the OGC Reference Model. The final deliverable of a “from scratch” focused SWG SHALL be a candidate Standard ready for submission using the OGC standards process.

For a SWG focused on processing a draft submission such as a specification developed outside the OGC and submitted into the OGC for consideration, the SOW would include evaluation of the submission in terms of the relationship to the existing OGC Standards baseline (see section below). The final deliverable of such a SWG SHALL be a candidate Standard for consideration by the membership for adoption.

For a SWG focused on revisions to an existing adopted Standard, the SOW should include a statement that the SWG will collect all outstanding Change Request Proposals (CRPs), evaluate each of the proposals, and make edits to the Standard based on CRPs and related decisions of the SWG membership. The SWG, at their discretion, may also ask the membership for any additional change requests that have not been previous submitted. Again, the final deliverable of a revision focused SWG SHALL be a revision of the candidate Standard for consideration by the membership for adoption.

In all cases, the SWG Charter shall provide a basic timeline plan for their activities.
////

The High Efficiency Image Format (HEIF) format supports the storage and containment of uncompressed and compressed forms of imagery, with supporting metadata. The GEOINT Imagery Media for ISR (GIMI) establishes a number of extensions to the HEIF format that include the ContentID, TAI Timestamps and Application metadata.
This SWG aims to standardize the GeoHEIF (Geographic High Efficiency Image Format) format based on HEIF, ISO base media file format (ISOBMFF) and the GIMI standards, to be used to represent orthorectified, georectified, and rectifiable imagery. In that sense, this SWG will concentrate efforts on producing an standard for geospatial metadata that can be encoded in HEIF format and other similar image formats such as GeoTIFF or JPEG2000.
Images can be geospatially enabled by providing coordinate reference system (CRS) metadata defined in Compact URIs (CURIEs), Well-Known Text version 2 (WKT2), or other OGC approved encodings. 
Using a _raster space to model space transformation matrix_, the image becomes georectified. Alternatively, a set of tie-points can be used to make the image georeferenceable.
Going beyond imagery, and considering the stacked gridded variables, by adding the definition of the semantics of dimensions and cell properties, the standard supports geospatial datacubes. Both dimensions and cell properties can be continuous, ordinal or categorical.

The scope of this SWG also includes containment of imagery with a broad range of array sizes, frame rates, one-to-many components (bands), variability in color formats, bit depths and, 2D dimension, or N dimension datacubes. This is a list of use case that this SWG should consider:

* Panchromatic or grey scale imagery
* Photographic or color imagery
* Multispectral satellite imagery
* Hyperspectral satellite imagery
* Orthophotography
* Stereogram imagery
* Timeseries imagery
* Model outputs imagery of continuous or categorical variables through time
* Astronomic or planetary imagery
* Synthetic Aperture Radar imagery

Adding other metadata and annotations to the HEIF, GeoTIFF, JPEG2000 etc is an important aspect that is in the scope of this SWG.

=== Statement of relationship of planned work to the current OGC Standards baseline

////
This section describes the relationship of the proposed standards activity to the existing Standards baseline. For the 3 cases:
If defining a new Standard, a statement of the relationship to the existing Standards baseline including statements related to overlap (if any) with existing OGC Standards functionality, harmonization issues, and so forth.

If processing change requests and performing a revision to an existing Standard, a simple statement to this effect shall be made.

If processing a draft submission of a specification developed outside the OGC process, a clear statement of the relationship to the existing Standards baseline including statements related to overlap (if any) with existing OGC Standards functionality, harmonization issues, and so forth. This information is provided to allow a focus of the discussion on criteria for considering any new solution that may be incompatible with older ones, overlaps existing functionality in the current baseline, and criteria for either deprecating older solutions, or simultaneously endorsing more than one option.
////

The spirit and approach of GeoHEIF is very similar to other efforts done with GeoTIFF and GMLJP2. They specify a way to include geospatial aspects in TIFF and JPEG2000 respectively. They will be inspirational for this SWG.  The result of the work of this SWG will take into account other gridded formats that can benefit from the same strategy such as GeoTIFF, GMLJP2, NETCDF, HDF, etc.

The work of this SWG is related to standards specifying services and APIs that can generate, expose or exchange geospatial coverages (such as OGC API coverages or OGC API processes) and it is foreseen that these services and API can serve GeoHEIF in the future. However, the way this is done in practice is out of scope of this SWG.

Part of the work of this SWG is related to the geodatacube SWG. The work of providing a text file format that can be embedded or accompany a gridded file will be done under the umbrella of the MetaCat DWG.

=== What is out of scope?

////
A short description of any activities that will be out of scope for the SWG. For example, a SWG may limit consideration of CRPs after a specified date or milestone.
////

Despite the capabilities of HEIF to store video, the scope of this SWG includes still and sequence imagery but does not consider motion imagery. The SWG will not define any API to retrieve GeoHEIF and will rely on other groups to do so, such as OGC API coverage. Eventually, this SWG can collaborate with the OGC API coverage to define an extension to better support GeoHEIF in OGC API coverage after finalizing the definition of the GeoHEIF format.

The work of this SWG should build on and leverages existing HEIF, ISOBMFF AND GIMI functionality including advanced codecs, image overviews, image tiling, and metadata. Those capabilities are not separately defined by this SWG, but can be used along with the geographical capabilities defined in this SWG.

=== Specific existing work used as starting point

////
This section provides reference information relevant to the work of the SWG. For example, a document reference for a draft submission or a list of CRPs for a SWG focused on revision to an adopted specification.
////

The work of this SWG will consider the OGC 24-038: GEOINT Imagery Media for ISR (GIMI) Specification Report. This document is a result of the work in Testbed 20 and was presented and approved in Rome in March 2025. This document has been written using the standards template (instead of the engineering report template) to facilitate the work of this SWG. The initial scope of this group is covered by the content of OGC 24-038. However, the group should consider additional inputs that will come from Testbed 21 that focuses on the Application Metadata capability defined in GIMI to include metadata in turtle format that can serve the same purpose but in a different way.

There are other documents result from the work of Testbed 20 about the same topic that can be useful for this SWG:

* OGC 24.039r1: OGC Testbed 20: GIMI Lessons Learned and Best Practices Report
* OGC 24-040r1:  OGC Testbed 20 Coverage Format Selection Report
* OGC 24-042r1:  OGC Testbed-20 GIMI Open Source Report
 

=== Is this a persistent SWG

[ ] YES

[X] NO

=== When can the SWG be inactivated

////
If this is not a persistent SWG, please define the criteria for determining when the SWG can be inactivated and the project archived. Please note that completion and archiving ensures that all files, wikis, emails, and so forth are archived and available for future viewing and use.
////

This SWG will be inactivated when the scope of the work has been finalized, the standard covering a common metadata to be embedded as well as the particularities of embedding it in GIMI have been approved and there are not open issued in the GitHub repository.

== Description of deliverables

////
This section describes what the deliverables will be for this SWG activity. Deliverables could be a revision to an existing Standard, including revisions to schemas. A deliverable could also be a best practices document.

This section also includes a preliminary schedule of activities. For example, an RFC focused SWG schedule would provide a plan and schedule that includes the start date, target date for release of the candidate Standard for public review, date for consolidation of comments, date for edits to document based on comments, and a final target date for making a recommendation to the Membership. This information will be made public and will also be used as input to a RoadMap for the document. Therefore, the more detail the better.
////

The main deliverable of this SWG is an OGC standard that specifies a common way of adding georeference to images and image sequences as well as how structure this images into a datacube. In addition, an OGC standard should specify GeoHEIF that will describe specifics on how to include the common way to include this type of metadata in HEIF. 
An additional document can be released as a second part of the standard discussing how to encode other metadata and annotations in the format.

=== Initial deliverables

////
Describe the initial Standard(s) to be developed by the SWG.
////
The initial deliverable of this SWG is an OGC standard that specifies a common way of adding georeference for images and image sequences and how structure this images into a datacube. This way will be compatible with the HEIF and the GIMI specifications.

=== Additional SWG tasks

////
Describe each additional Standard to be developed by the SWG as an additional task after the deliverables from the initial charter have been completed. This section is blank in a new charter, then is populated with each task approval request per the OGC TC Policies and Procedures.
////

This SWG will collaborate with OGC API coverages SWG to ensure that GeoHEIF can be served by the web API

This SWG will collaborate with GeoTIFF SWG, GMLJP2 SWG and other SWGs dealing with gridded formats to ensure that the common way of adding metadata can be accepted by those relevant formats. This may include
generation of a logical model for georeferencing, and specific encodings of that logical model that are consistent with the underlying raster or coverage format.

This SWG will consider generating educational materials and guidelines on GeoHEIF and to create a GeoHEIF website to include them as well as listing applications and implementations of GeoHEIF.

== IPR Policy for this SWG

[x] RAND-Royalty Free

[ ] RAND for fee

== Anticipated audience / participants

////
Description of the target participants in this SWG. For example, if the SWG were focused on a candidate spatial query language standard: Those involved in the design, development, implementation, or use of elements listed above in "Scope of the Work".  This includes search service providers, prospective users of search services exposed as XML, information architects and bibliographic, metadata, and content provider.

This is not meant as a limiting statement but instead is intended to provide guidance to interested potential participants as to whether they wish to participate in this SWG.
////

We expect participation of people interested in gridded coverage formats, such as remote sensing experts as well as participants interested in encoding geospatial datacubes in files, for example modelers of environmental variables (a.k.a observed properties) such as weather, climate and oceans experts. We also expect that GIMI community will collaborate in this SWG.

== Domain Working Group endorsement

////
The SWG will list all Domain Working Groups (DWGs) in which the SWG formation was discussed and/or chartered. If a DWG has specifically endorsed the formation of the SWG, then a statement of endorsement should be included.
////

The GeoTIFF SWG is the initial group where the creation of this SWG is discussed. We would like to request the endorsement of the MetaCat DWG

== Other informative information about the work of this SWG

=== Collaboration

////
Describe the work environment of the SWG, including the use of GitHub or GitLab.
////

The OGC supporting infrastructure is in the process of evolution to new technologies and it is difficult to predict the working environment at this point. We expect to use GitHub to develop the standard in asciidoc format (and metanorma) as well as the GitHub issue tracker to manage content and change requests. The group will internally discuss if making the GitHub repository public is acceptable by all parties.

=== Similar or applicable standards work (OGC and elsewhere)

The following Standards and projects may be relevant to the SWG's planned work, although none currently provide the functionality anticipated by this committee's deliverables:

* GeoTIFF
* GMLJP2
* O&M and SOSA

The SWG intends to seek and if possible maintain liaison with each of the organizations maintaining the above works.

=== Details of first meeting

////
Example:
The first meeting of the SWG will be held by telephone conference call at 10AM EDT on 1 October 2007. Call-in information will be provided to the SWG's e-mail list and on the portal calendar in advance of the meeting.
////
The first meeting of the SWG will be held immediately after the approval of the charter (this document) in OGC meeting in Boulder in October 2025. Call-in information will be provided to the SWG's in the OGC Agora in advance of the meeting.

=== Projected on-going meeting schedule

////
Example:
The work of the SWG will be carried out primarily by email and conference calls, possibly every two weeks, with face-to-face meetings perhaps at each of the OGC TC meetings.
////
The work of the SWG will be carried out primarily by discussions in the OGC Agora, GitHub issues and conference calls, possibly every month, with face-to-face meetings at some of the OGC Members Meetings.

=== Supporters of this Charter

The following people support this proposal and are committed to the Charter and projected meeting schedule. These members are known as SWG Founding or Charter members. The charter members agree to the SoW and IPR terms as defined in this charter. The charter members have voting rights beginning the day the SWG is officially formed. Charter Members are shown on the public SWG page. Extend the table as necessary.

|===
| Name       | Organization
| Joan Maso  | UAB-CREAF
| Brad Hards | Silvereye Technology
|===

=== Conveners

////
Name of individual(s) who started the SWG process. Could be the lead for an RFC submission, an OGC staff person, or an individual who believes it is time for a revision to an adopted Standard.
////
Joan Maso and Nuria Julia are the initial conveners of the SWG but chairs will be elected in the first SWG meeting.

== References

////
Optional list of references.
////
* OGC 24-038: GEOINT Imagery Media for ISR (GIMI) Specification Report
* OGC 24.039r1: OGC Testbed 20: GIMI Lessons Learned and Best Practices Report
* OGC 24-040r1:  OGC Testbed 20 Coverage Format Selection Report
* OGC 24-042r1:  OGC Testbed-20 GIMI Open Source Report
