:Title: OGC Hydrology Domain Working Group Charter
:titletext: {Title}
:doctype: book
:encoding: utf-8
:lang: en
:toc:
:toc-placement!:
:toclevels: 4
:numbered:
:sectanchors:
:source-highlighter: pygments

<<<
[cols = ">",frame = "none",grid = "none"]
|===
|{set:cellbgcolor:#FFFFFF}
|[big]*Open Geospatial Consortium*
|Submission Date: <yyyy-mm-dd>
|Approval Date:   <yyyy-mm-dd>
|Internal reference number of this OGC(R) document:    YY-nnnrx
|Category: OGC(R) Domain Working Group Charter
|Authors:   David Blodgett, Sylvain Grellet, Eric Boisvert
|===

[cols = "^", frame = "none"]
|===
|[big]*{titletext}*
|===

[cols = "^", frame = "none", grid = "none"]
|===
|*Copyright notice*
|Copyright (C) 2025 Open Geospatial Consortium
|To obtain additional rights of use, visit http://www.opengeospatial.org/legal/
|===

<<<

== Introduction

This Domain Working Group (DWG) charter defines the role for OGC activities within the hydrology domain and to provide an open forum for the discussion and presentation of interoperability requirements, use cases, pilots, and implementations of OGC Standards in this domain. This Charter is to be presented to the OGC’s Technical and Planning Committees for consideration.

Domains are distinct Information Communities that defines a user domain where:

* A distinct market, application, or business approach exists;

* Common data definition, structure, syntax, and definitions exists;

* Common user requirements exist; and/or

* Common approach to vendors exists

=== Working Group

Operation of OGC Domain Working Group follows the policies and procedures of the Technical Committee.  The following definition from the Technical Policies and Procedures apply to this DWG Charter template.

*Domain Working Group*: A group (organizationally, a subgroup of the TC) of individuals composed of members of the TC and invited guests, with the specific intent of solving some particular interoperability problem or problems in a particular technology domain for recommendation to the Technical Committee.

Functions of a Domain Working Group are as follows.

* Provide a forum for discussion and documentation of interoperability requirements for a given information or user community.
* Provide a forum to discuss and recommend document actions related to Interoperability Program Reports.
* Develop Change Requests Proposals (CRPs) for existing OGC Standards.
* Develop engineering reports with the intent seeking approval by the TC for release of these documents as OGC White Papers, Discussion Papers or Best Practices Papers.
* Informational presentations and discussions about the market use of adopted OGC Standards.
* Have a formal approved charter that defines the DWGs Scope of Work and estimated timeline for completion of the work.
* Have all-member voting policies (unless otherwise stated).
* Have missions and goals defined by the TC.

A DWG [underline]#Does Not# work on Standards submissions, candidate Standards, or revisions to existing OGC Standards. However, a DWG can develop change requests as document interoperability requirements that can then be submitted as work items to a Standards Working Group (SWG).

A DWG may determine that they wish to have public collaboration, such as in teleconference, email discussions, or a public twiki. In this case, the DWG shall make a motion to the TC to approve public participation in the DWG. Voting in DWGs is by simple majority of OGC Members present at the WG meeting, not just Voting TC Members, with the caveat that no OGC Member organization may cast more than one vote in a WG vote.

== Purpose of Working Group

The purpose of the Hydro DWG is to provide a venue and mechanism for seeking technical and institutional solutions to the challenge of describing and exchanging data describing the state and location of water resources, both above and below the ground surface. The path to adoption will be through OGC papers and standards, advanced to ISO where appropriate, and also through the World Meteorological Organizations (WMO).  While WMO Technical Commissions have the recognized mandate to publish and promote standards in this area, OGC contributes to the process with its resources and experience in guiding collaborative development among disparate participants in a rapidly evolving technological environment. It is proposed that the OGC Hydrology DWG will provide a means of developing candidate standards for submission to ISO and for adoption by INFCOM as appropriate.

This charter is an updated version of the original Hydrology Domain Working group (HydroDWG) charter written in 2009.  The original proposal for this working group came about when CUAHSI (Consortium of Universities for the Advancement of Hydrologic Science) and  (Commonwealth Scientific and Industrial Research Organisation) teams discovered they were working on similar problems and that an international approach to the problem space would potentially have greater benefits than each team continuing alone.  More than 15 years after this foundational document, most of the motivations that led to the creation of this working group remain intact.  While the technological landscape has evolved, the need for timely and effective exchange of water information remains critical. With climate change, population growth, and economic demands placing mounting pressure on water resources, water scarcity is becoming increasingly evident.  

The Hydrology Domain Working Group has brought together interested parties to develop and promote technology for greatly improving the way in which water information is described and shared.  A suite of standards were developed to address the exchange of timeseries, surface and groundwater features, sections, ratings and gauges, collectively referred to as "WaterML2".  However, the technological landscape has moved on and some of the technologies refered in the 2009 charter have evolved. The time has come for this working group to revisit past achievements and consider them in the light of new trends in web and emerging technologies such as spatial data on the Web, Artificial Intelligence, and Digital Twins.  

This motivated the revision of the original charter to reflect the current and future needs of the hydrology domain.  The HydroDWG will continue its mission of providing a venue of exploring and dissiminating technical and institutional solutions and will take stock of the current state of the art and propose a path forward with legacy products.

== Problem statement

Hydrology is the study of water, whether flowing above ground, frozen in ice or snow, retained by soil or moving through geological units.  Effective water management requires sound and reliable data. However water information is highly spatial, highly temporal and is created and managed across multiple organizations and levels of governments.  Water flows across borders and jurisdictions. Decisions of one impact many.
 
Around the world, agencies collect and manage water information to support policy development, planning, research, and financial decisions. The heterogeneity of sampling methods, protocols, spatial and temporal distributions is a challenge for users to access and use.  In addition, new information sources in the form of in-situ and remote sensors are coming on line and telecommunications and computing technology has improved to the point that information about water resources can be analysed and predicted in real-time. This data is critical for many diverse groups, ranging from national agencies to private landholders to financial institutions. In addition, the increasing use of Artificial Intelligence, Digital Twins to support policies and decision making requires vast amounts of data to be ingested rapidly. A veritable flood of water information is now available. 
 
However, there is no broadly accepted comprehensive suite of structured definitions or interoperable formats to package information. The problem is two-fold:

  * Firstly, a consistent set of definitions that reflect core hydrologic features (e.g. watersheds, estuaries, river channels, aquifers, different types of measurement points), common types of hydrologic sampling features (e.g. transects, vertical profiles), typical ways of organizing hydrologic data (e.g. time series, remote sensing), and typical usage scenarios for hydrologic data are needed. 
  * Secondly,general and consistent encoding patterns to ensure hydrologic data can be moved across systems and disciplines.  

Between 2009 and 2024, the Hydrology Domain Working Group worked to advance conceptual and technical solutions for general water resources data interoperability through a multi-part WaterML2 suite of standards. Drawing from the OGC abstract specification conceptual baselines for features, observations, spatial features, and coverages and defining hydrology-specific conceptual models for river monitoring, surface water, and groundwater. Some of these efforts resulted in implementation specifications providing XML schema as transfer formats. The WaterML2 suite of standards is generally consistent from a conceptual perspective but has not been implemented as a consistent  XML or JSON schemas or other physical format specifications. 
 
Efforts toward OGC-APIs have advanced multi-disciplinary interoperability and further consideration is needed toward mechanisms to include various datasets and services from related disciplines (e.g., atmospheric science and meteorology, and ocean observation) which are essential for water resources monitoring and analysis. Hence, a consistent method is needed for modeling and encoding water resources information based on the robust technical base provided by OGC-API standards, W3C Spatial Data on the Web best practices, and other related interoperability/FAIR principles.

It is important to note that WMO expects harmonised and tested data models for all types of water resources world-wide. To achieve this, of a suite of approaches that pragmatically address and provide guidelines for water resources data and metadata holistically must be established.

Since the publication of the current version of Water 2.0 suite, models upon which they depend continued evolving, and a shift from XML to JSON has been operated.  A number of adopted and emerging OGC, W3C and ISO standards now needs to be considered by the working group.

  * GEOJSON – encoding standard for geospatial feature data
  * CoverageJSON – encoding standard for geospatial coverage data
  * OGC-API
  * OMS – Observations Measurements and Samples
  * SensorThings – interface for hosting and accessing observation data
  * W3C SOSA/SSN
  * W3C CSV for the Web (CSVW)

In order to apply these OGC and ISO standards to the water resources domain, they need to be profiled appropriately. It is expected that a significant part of the standard work undertaken through the Hydrology DWG will focus on this task. Existing WaterML2 standards relying on XML schema need to be updated to use these specifications and/or compatible technologies (JSON-Schema and JSON-LD Context in place of XML-Schema and OWL Ontology). 
 
The advent of W3C Spatial Data on the Web Best Practices and efforts toward increasingly ubiquitous semantic web technologies such as "Science on schema.org" and the two OGC "Environmental Linked Features Interoperability Experiments" are key advances to build on. Specification of standards and best practices that allow Hydrology domain concepts to be encoded in linked data for consumption by Web crawlers and use in knowledge graph applications is a high value opportunity.


////
The problem(s) associated with interoperability and geodata processing as they relate to the DWG needs to be defined.  The WG DOMAIN information community needs to be defined, (users, data, service, and technology providers).  Problems might be framed as barriers that need to be overcome.  It is these barriers that will ultimately suggest the nature of the OGC’s role and level of involvement and lead to a set of processes, activities, and organizational approaches whereby the DOMAIN community can, through OGC, come together to develop a common means for digitally representing and sharing domain related geospatial data, and for processing interoperability within mainstream information system environments.
////

== Charter

The charter of this Working Group is to address conceptual, technical and institutional challenges posed by management and exchange of hydrological information, to interface with other OGC working groups which address technical areas that are affected by the hydrology problem, and to engage in outreach and communication with the hydrological information community. 

==== Chairs

This working group is hosted by the OGC and co-chaired by up to three representatives elected by members of the HydroDWG. The working group will coordinate efforts with other earth science DWGs (Meteorology, Oceans, etc) through the Earth System Science DWG.

==== Members

The Hydrology DWG will be a joint working group between the OGC and WMO. The group will be co-chaired by OGC members elected by the DWG members and up to two representatives nominated by WMO. The same person can simultaneously represent OGC and WMO.  
Membership of the group will be open to any OGC and WMO members at any time, in accordance with the OGC Policies and Procedures. WMO may also nominate non-OGC members to participate in the group. This will provide an open forum for work on water data interoperability, and a route to publication through OGC's standards ladder (Discussion paper / Best Practice / Standard/ ISO Standard) as well as a route to adoption by the WMO.


=== Key activities

The Hydrology DWG will maintain a forum for discussion and documentation of interoperability requirements for the hydrological information community and recommend actions. It will liaise with other OGC working groups and external organizations to ensure that the needs of the hydrological information community are addressed and support other working groups in addressing hydrological information requirements.

The Hydrology DWG will coordinate and steer the work of its Standards Working Groups (SWGs) to harmonize and modernize the WaterML2 series of standards developed since 2009.   The DWG will also oversee the publication of engineering reports and new additions to the WaterML2 suite. 

The DWG will also engage in outreach and communication with the hydrological information community through the development of training material and  documents addressing specific technical problems in the hydrology domain.  The DWG will grow the community by engaging members the hydrological community.


=== Business case

Growing water crises of various natures around the world have challenged our ability to describe water resources (and hydrological hazards) and transfer information adequately. Increasing anthropogenic pressure, climate change and numerous other challenges are putting greater demands on what is already a scarce resource. Advances in data integration and modelling (machine learning, digital twins, dataspaces, etc.) dramatically increase the value of organized and coherent water data.

Collaboration requires agreements and to move data across, standards and technologies must be created. The former Hydrology Domain Working Group (HydroDWG) has brought together interested parties to develop and promote technology for greatly improving the way in which water information is described and shared.  A suite of standards were developed to address the exchange of timeseries, and describe sections, ratings and gauges. Models were proposed for surface and groundwater features.  The time has come for this working group to revisit past achievements and consider them in the light of new trends in web and emerging technologies such as spatial data on the Web, Artificial Intelligence, and Digital Twins.  

A key for water management is the ability to measure and share information about it. Groups around the world develop tools for water information. For many reasons, this work has concentrated on specific problems with little concern for broader applicability. In recent times, the need to think more broadly has become important.



////
Define the business case related to interoperability that confront the DOMAIN community. Examples of issues that might be discussed include:

* GeoData and support data taxonomy and characterization
* Data sharing, interface standards and approaches
* Metadata standards
* DOMAIN analysis models and processing standards
* Data quality and accuracy
* Data protection and truth in labeling
* Data acquisition coordination
* User education

Define the business case that requires resolution because businesses that are engaged in DOMAIN related activities view them as an obstacle for growth.

Define what measures OGC should consider for developing guidelines that address business case issues and that lead to or suggest that process-related standards and other intervention strategies available via consortia approaches will best support the infrastructure of the information community to come together and to inform information community consumers.
////

== Organizational approach and scope of work

=== Business goals

The primary goals for OGC in the area of hydro information are to foster a FAIR/interoperability water community and make the HydroDWG the forum for this community.

Therefore this community
  * shares common issues and explore solutions via open standardized approaches and tools,
  * develops technical and semantics standards based on the OGC Baseline (extending it as required) in a coordinated manner,
  * transfers solutions to its members through tools and training,
  * helps members to leverage OGC standard development, testing and demonstration framework to coordinate activities at regional / national / continental / international and organizational levels to achieve FAIR objectives,
  * brings stakeholders from
  * Public sector monitoring, 
  * NGO
  * Research and academic organizations, 
  * Private sector
  * Software vendors and open source community


////
The <DOMAIN WG> will need to establish a set of business goals that frame the basis for determining the nature and type of recommendations made to OGC, framed around the above mentioned business issues.  Examples of the types of discussion for framing goals include

1.	Efforts should focus on working <DOMAIN> issues and problems that result in a net gain for the community.

2.	Minimize technical distinctions between <DOMAIN> data processing systems that use geography, as this can lead to artificial barriers that limit the potential of all segments of the information community to come together and fully prosper.

3.	Avoid placing artificial technical barriers on use of <DOMAIN> data.

4.	Establish the means by which OGC can achieve interoperability and yet preserve the proprietary nature of data.

5.	Define the supporting infrastructure for the community to achieve these goals.
////

=== Mission and Role

The mission of the Hydrology DWG is to faciliate the exchange of hydrological date through the development of standards, best practices and education material. The Hydrology DWG will provide a forum for discussion and coordination for the hydrological information community and recommend actions. 

The Earth System Science DWG is the forum for coordinating activities and documents produced by domain specific earth science DWGs, including Hydrology.

The Hydrology DWG will have up to three co-chairs, who will coordinate the activities and the agenda for OGC meetings. One co-chair will represent WMO. Membership of the Hydrology DWG is open but chairs reserve the right to grant access to the DWG based on relevance and capacity.
As development projects emerge, the specification editor(s) will be selected from the WG members. Members of related Standard Working Groups will be open to OGC members, and members of organizations affiliated with or working on projects for WMO. 


=== Activities planned for HydroDWG


In the course of fulfilling its Charter, the Hydrology DWG will envision a series of short-term and medium-terms activities. Short-term activities can begin immediately, medium-term activities require revision of standards and domain models.

In the short-term, the HydroDWG will:

. Support its SWGs to publish modern encodings, specifically JSON/JSON-LD encoding but others might be considered.
. Support the SWGs to 
.. update WaterML2.0 Part1: Timeseries dependencies from O&M v.2 to Observations, Measurements and Samples (OMS),
.. update the SensorThings API to version 2.0 taking into account the Water Quality IE Recommendations and 
.. the publication of a WaterML2.0 Part 5: WaterQuality document  (standard VS best practice still to be defined) building on the WaterQuality IE Engineering Report.
. Develop communication materials: Describe and link documentation, training materials and other documents focussing on the technical problem area of hydrological data management and exchange.
.. Provide a public communication hub: Manage a Github-based project for discussions, issue tracking and artifacts management (schemas, documentation, examples, code). 
.. Grow the community: engage members of the geospatial data community (including relevant OGC working groups) and the hydrological community (OGC members and non members). Foster and mediate communication within this target audience.
.. Establish an activity road map: Conceive, design, coordinate a road map for demonstrations, pilots, interoperability experiments in its perimeter of activity.
. As appropriate, serve as a forum for the development of specification profiles and application schemas for hydrological purposes.
. Engage the interest of sponsors for these activities.

In the medium term

. The Hydro DWG will steer its SWGs to improve uptake. Several models require simplification, better tooling and better documentation and training.
. Develop a “lite” encoding conformant to GML Level 0 representing key features of relevant standards, as proposed by GeoSciML (OGC 16-008). 
. Simplify and create  a logical model for  HY_Feature.
. Align current standards to new versions of dependencies (such as O&M v.2 to Observations, Measurements and Samples).
. Help support development of tools of the related standards
. Consider extending the WaterML2.0 line to other water domains (ex : rain/waste water networks)
. Develop hydrological ontologies based on existing OGC and W3C standards and existing ontologies to enhance interoperability and linked data exchange.
. Expand the Water Quality Work  to biodiversity and earth observations and explore joint vocabularies
. Explore development of  joint vocabularies for HY_Features and GWML 2
. Launch a follow-up Water Quality Interoperability Experiment (WQ IE  n°2) to consider the excluded Use Cases.




////
Define scope of work and tasks in terms of interoperability approaches for OGC Technical Committee consideration, define how this is to complement existing efforts and results produced by the OpenGIS Project, resulting in a specification for all forms of geospatial data and geoprocessing services. The following points should be discussed under scope of work and tasks.

1.	Define how the DWG will act as an impetus for the creation of whole new modes of operation and economic behavior which will influence the way businesses and governments operate in DOMAIN business activity. These could include business rules, standards and interfaces that must be common across a multidisciplinary and fragmented geographic information community, as well as conformance processes pertaining to DOMAIN data and technology.

2.	Define DWG membership objectives.

3.	Define how user communities, both current and potential, should have access to the working group so that requirements and technology issues are addressed and results do indeed provide the technology they need.

4.	Define technical tasks to be undertaken by the DWG.
////

== References


   * GeoJSON Format Specification, RFC 7946, IETF, URL https://datatracker.ietf.org/doc/html/rfc7946.
   * WaterML 2.0 Part 0 - OGC WaterML 2.0 suite, URL https://www.ogc.org/standards/waterml/.
   * WaterML 2.0 Part 1 - Time Series (1.0), OGC Document 10-004r3, URL https://portal.ogc.org/files/?artifact_id=57222.
   * WaterML 2.0 Part 2 - Ratings, Gaugings and Sections (1.0), OGC Document 10-007r3, URL https://docs.ogc.org/is/15-018r2/15-018r2.html.
   * WaterML 2.0 Part 3 - Hydrologic Features (1.0), OGC Document 10-005r3, URL https://docs.ogc.org/is/14-111r6/14-111r6.html.
   * WaterML 2.0 Part 4 - Groundwater (1.0), OGC Document 10-006r3, URLhttps://docs.ogc.org/is/16-032r2/16-032r2.html.
   * CoverageJSON, OGC Community Standard, URL https://covjson.org/.
   * OGC API Standards, OGC, URL https://ogcapi.ogc.org/.
   * Observations Measurements and Samples, OGC Abstract Specification Topic 20, URL https://docs.ogc.org/as/20-082r4/20-082r4.html
   * OGC SensorThings API, URL https://www.ogc.org/standards/sensorthings
   * Semantic Sensor Network Ontology, W3C Recommendation, URL https://www.w3.org/TR/vocab-ssn/
   * W3C CSV for the Web (CSVW), W3C Recommendation, URL https://www.w3.org/TR/tabular-data-model/

////
Optional list of references.
////


